# Generated by Django 3.2.15 on 2022-09-18 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[6789]\\d{9}$')]),
        ),
    ]
