# Generated by Django 3.2.15 on 2022-09-17 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_image'),
        ('products', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('orderDate', models.TimeField()),
                ('product_id_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.product')),
                ('user_id_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('product_id_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='products.product')),
                ('user_id_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
